apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport-pod
  labels:
    app: nginx-node-port
    demo: service
spec:
  containers:
  - name: nginx-nodeport-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx-node-port
    demo: service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    

