apiVersion: v1
kind: Pod
metadata:
  name: nginx-loadbalancer-pod
  labels:
    app: nginx-loadbalancer
    demo: service
spec:
  containers:
  - name: nginx-loadbalancer-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-loadbalancer
    demo: service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    

