apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi: 
    driver: ebs.csi.aws.com
    volumeHandle: fs-0e772f96b189b64df
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    demo: efs-static-label
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-efs
      mountPath: /usr/share/nginx/html
  # nodeSelector:
  #   zone: 1c
  volumes:
  - name: nginx-efs
    persistentVolumeClaim: 
      claimName: ebs-static-pvc
---
apiVersion: v1 
kind: Service
metadata:
  name: efs-static-service
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static-pod
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
