# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   # name: efs-static-pv
#   name: efs-static
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   csi: 
#     driver: ebs.csi.aws.com
#     volumeHandle: fs-0e772f96b189b64df
# ---
# apiVersion: v1 
# kind: PersistentVolumeClaim
# metadata:
#   # name: efs-pvc
#   name: efs-static
# spec:
#   # volumeName: efs-static-pv
#   accessModes:
#     - ReadWriteOnce
#   volumeName: efs-static
#   resources:
#     requests:
#       storage: 4Gi
# ---
# apiVersion: v1 
# kind: Pod
# metadata:
#   # name: efs-static-pod
#   name: app
#   labels:
#     # demo: efs-static-label
#     demo: efs-static
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     volumeMounts:
#     - name: nginx-efs
#       mountPath: /usr/share/nginx/html
#   nodeSelector:
#     zone: 1c
#   volumes:
#   - name: nginx-efs
#     persistentVolumeClaim: 
#       # claimName: ebs-pvc
#       claimName: efs-static
# ---
# apiVersion: v1 
# kind: Service
# metadata:
#   # name: efs-static-service
#   name: efs-static
# spec:
#   type: LoadBalancer
#   selector:
#     # demo: ebs-static-pod
#     demo: efs-static
#   ports:
#   - protocol: TCP
#     port: 80 
#     targetPort: 80

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e772f96b189b64df
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: efs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1b
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: efs-static
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static
spec:
  type: LoadBalancer
  selector:
    demo: efs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port
    



