apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi: 
    driver: ebs.csi.aws.com
    volumeHandle: fs-05fc947e9b605d8cb
---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc  # Corrected to match the PVC name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1 
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    demo: efs-static-label
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-efs
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1d
  volumes:
  - name: nginx-efs
    persistentVolumeClaim: 
      claimName: efs-static-pvc  # Corrected to match the PVC name
---
apiVersion: v1 
kind: Service
metadata:
  name: efs-static-service
spec:
  type: LoadBalancer
  selector:
    demo: efs-static-label
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
