apiVersion: v1
kind: Pod
metadata:
  name : multi-container
spec:
  containers:
  - name: multi-container-1
    image: nginx
    ports:
    - containerPort: 80
  - name : multi-container-2
    image: almalinux:8
    command: ["sleep", "100"]

