apiVersion: v1
kind: Pod
metadata:
  name : annotaions-demo
  labels:  # only to call inside resources like services and all etc ...
    course: DevOps
    trainer: "sivakumar"
  annotations:
    com.roboshop.training.duration: "120_Hrs"   #key value pairs anything we can mention ext values
    jenkins.url: "https://jenkins/roboshop/catalogue#45"
spec:
  containers:
  - name: annotaions-demo-practice
    image: nginx
    ports:
    - containerPort: 80
