apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  containers:
  - name: first-pod
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests: 
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

