# apiVersion: v1
# kind: Pod
# metadata:
#   name: first-pod
# spec:
#   containers:
#   - name: first-pod
#     image: nginx:latest
#     ports:
#     - containerPort: 80
#     resources:
#       requests: 
#         cpu: "100m"
#         memory: "68Mi"
#       limits:
#         cpu: "200m"
#         memory: "128Mi"

apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  # list of containers
  containers:
  - name: hello-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"