apiVersion: v1
kind: Pod
metadata:
  name: config-pod

spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:                 #by using each key value 
    - name: COURSE
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: course
    - name: TRAINER
      valueFrom:
        configMapKeyRef:
          name: devops-config
          key: trainer
---           #by using file directly all env applicable
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-1

spec:
  containers:
  - name: config-pod-1
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMap`Ref:
          name: devops-config 
